name: Reject improper pull/merge requests

on:
  pull_request:
    branches:
      - main

jobs:
  reject-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in README.md and prompts.csv
        run: |
          if git diff --quiet HEAD^ README.md prompts.csv
          then
            echo "::error file=README.md,line=1::No changes to README.md and prompts.csv"
            exit 1
          fi

      - name: Check for required contributor message
        run: |
          if ! grep -q "Contributed by: \[@.*]\(https:\/\/github\.com\/.*\)" README.md
          then
            echo "::error file=README.md,line=1::Required contributor message not found in README.md"
            exit 1
          fi

      - name: Exit with error if checks fail
        if: ${{ failure() }}
        run: |
          echo "::error::One or more checks failed, please make sure to follow the contribution guidelines in the README file."
          exit 1
